"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

import middle

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fvbc)yj=t4^e9warv7f-ht5oynac-(su9m(&qs3dtvz2tp_b-1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'ckeditor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'main',
    'plugin.point.apps.PointConfig',
    'plugin.invite.apps.InviteConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'middle.AuthMiddle',
]

# if DEBUG:
#     INSTALLED_APPS.insert(0, 'debug_toolbar')
#     MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
#     INTERNAL_IPS = ['127.0.0.1']

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'newshop',
        'USER': 'root',
        'PASSWORD': 'a;?qVZ11',
        # 'HOST': '127.0.0.1',
        'HOST': '47.96.94.0',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': 'SET character_set_connection=utf8mb4;'
                            'SET collation_connection=utf8mb4_unicode_ci;'
                            "SET NAMES 'utf8mb4';"
                            "SET CHARACTER SET utf8mb4;"
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'main.Merc'


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'  # 模板渲染时区

USE_I18N = True

USE_L10N = True

# USE_TZ = True  # 数据存储与处理都用utc，只有模板显示为设置时区


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # 静态文件生成目录


#  七牛云相关配置
QINIU_ACCESS_KEY = 'wQ7NXgSlApMSVa7bezckCrHLJDEcY6hkXpUbyfAQ'
QINIU_SECRET_KEY = '3IKSgxwe_wIL-c7R-xi-oFRu7gbB1I04TjdXrAlG'
QINIU_BUCKET_NAME = 'img'
QINIU_BUCKET_DOMAIN = 'img.renheyoudao.com'
QINIU_SECURE_URL = False  # 使用http
PREFIX_URL = 'http://'
DEFAULT_FILE_STORAGE = 'qiniustorage.backends.QiniuMediaStorage'

#  媒体文件保存
MEDIA_URL = PREFIX_URL + QINIU_BUCKET_DOMAIN + '/media/'
MEDIA_ROOT = 'media'


QRCODE_URL = '/media/'  # 请求相对路径
# QRCODE_ROOT = os.path.join(BASE_DIR, 'media')
QRCODE_ROOT = '/var/tanku/media/media'


# ckeditor
CKEDITOR_UPLOAD_PATH = 'uploads/'


SIDE_MENU = (
    ('订单管理', ('main.Order', 'main.OrderRefund')),
    ('商品管理', (
        'main.Sku',
        ('商品类别', ('main.Cate', 'main.Cate2')),
        'main.Tag',
        'main.Brand')),
    ('用户管理', ('main.User',)),
    ('店铺管理', ('main.Shop', 'main.Ship')),
    ('营销管理', ('main.Coupon',)),
    ('分享数据', ('share.Mark', 'share.Record'))
)


# 分页数量
# ORDER_PAGE_NUM = 20
ORDER_PAGE_NUM = 10


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # 简单的日志格式
        'standard': {
            'format': '[%(asctime)s][%(levelname)s]%(message)s <- %(filename)s:%(lineno)d'
        }
    },

    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
    },

    # 定义各种logger以分别处理不同模块
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True
        },
        # 'django.db.backends': {
        #     'handlers': ['console'],
        #     'level': 'DEBUG',
        #     'propagate': True
        # }
    }
}

# 测试回调地址
NOTI_URL = 'http://jkb.tankuwang.net/payNoti'

HOST_URL = 'https://jkb.tankuwang.net'



